name: Build & Release

on:
  push:
    branches:
      - source

permissions:
  contents: write
defaults:
  run:
    shell: bash

jobs:
  prepare-cv:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: inject git tag into CV
      run: |
        cd static/cv
        echo "LINE25 (BEFORE injecting version):"
        cat cv-lihs.tex| head -n 25 | tail -n 1
        git rev-list --abbrev-commit -1 HEAD cv-lihs.tex > .COMMIT_SHA
        export COMMIT_SHA=$(cat .COMMIT_SHA)
        sed -i.bak "s/\({git:\)[[:alnum:]]*\(}\)/\1"$COMMIT_SHA"\2/" cv-lihs.tex
        cp cv-lihs.tex cv-lihs-print.tex
        sed -i.bak "s/\([[:alnum:]]*documentclass\[\)\([[:alnum:]]*\)\(\]{friggeri-cv}.[[:alnum:]]*\)/\1print\2\3/" cv-lihs-print.tex
        echo "LINE25 (AFTER injecting version):"
        cat cv-lihs.tex| head -n 25 | tail -n 1
    - name: Upload modified tex
      uses: actions/upload-artifact@v3
      with:
        name: cv-tex
        path: |
          static/cv/cv-lihs.tex
          static/cv/cv-lihs-print.tex
        retention-days: 7

  build-cv:
    needs: prepare-cv
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/michaellihs/texlive
    steps:
    - uses: actions/checkout@v2
    - name: Download modified tex
      uses: actions/download-artifact@v3
      with:
        name: cv-tex
        path: static/cv/
    - name: run LaTeX build (web)
      run: |
        cd static/cv
        lualatex cv-lihs.tex
        lualatex cv-lihs.tex
    - name: run LaTeX build (print)
      run: |
        cd static/cv
        lualatex cv-lihs-print.tex
        lualatex cv-lihs-print.tex
    - name: Upload modified tex
      uses: actions/upload-artifact@v3
      with:
        name: cv-pdf
        path: |
          static/cv/cv-lihs.pdf
          static/cv/cv-lihs-print.pdf
        retention-days: 7
    - name: Upload pdf to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: static/cv/cv-lihs.pdf
        asset_name: cv-michael-lihs.pdf
        tag: ${{ github.ref }}
        overwrite: true
        body: "Current CV of Michael Lihs"

  # generate-page:
  #   needs: build-cv
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: anoff/hugo-asciidoctor
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Download generated CV
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: cv-pdf
  #   - name: add tar APK for running actions/cache@v3
  #     run: |
  #       apk add --no-cache tar
  #       ls -ahl _site/
  #   - name: Upload HTML
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: website
  #       path: _site/
  #       retention-days: 7

  # deploy-page:
  #   if: github.ref == 'refs/heads/source'
  #   needs: generate-page
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Download HTML
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: website
  #       path: _site/
  #   - name: Publish page
  #     uses: JamesIves/github-pages-deploy-action@v4
  #     with:
  #       folder: _site
  #       branch: master
